version: '3'

services:
  graalvm-project:
    image: graalvm-project:latest
    container_name: JavaSoftTestApp-container
    build:
      context: ../
      dockerfile: ./environments/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/JavaCodeTest?useSSL=false
      - SPRING_DATASOURCE_USERNAME=userJavaCode
      - SPRING_DATASOURCE_PASSWORD=passJavaCode
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    container_name: JavaCodeTest
    restart: on-failure
    environment:
      - POSTGRES_USER=userJavaCode
      - POSTGRES_PASSWORD=passJavaCode
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: pg_isready -Utest_user
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  db: { }